version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:21-jdk
orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
