server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8010/eureka
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name:
      Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id:
            user-status
          uri:
            lb://User-Service
          predicates:
            - Path=/users/status
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id:
            get-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/{userId}
            - Method=GET
          filters:
            - AuthorizationHeaderFilter
        - id:
            get-users
          uri:
            lb://User-Service
          predicates:
            - Path=/users
            - Method=GET
        - id:
            create-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users
            - Method=POST
        - id:
            update-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/{userId}
            - Method=PUT
          filters:
            - AuthorizationHeaderFilter
        - id:
            delete-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/{userId}
            - Method=DELETE
          filters:
            - AuthorizationHeaderFilter
        - id:
            user-login
          uri:
            lb://User-Service
          predicates:
            - Path=/users/login
            - Method=POST
token:
  expiration: 3600000
  secret: CYDblORrZAKg7i23rKlMi2lcwes9lUd8Q3D1GD1ViBm1NPvEKNnXGY6Fno7Ob8Vz