server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8010/eureka
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name:
      Api-Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id:
            user-status
          uri:
            lb://User-Service
          predicates:
            - Path=/users/status
          filters:
            - RemoveRequestHeader=Cookie
#            - AuthorizationHeaderFilter
        - id:
            get-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/{userId}
#          filters:
#            - AuthorizationHeaderFilter
        - id:
            get-users
          uri:
            lb://User-Service
          predicates:
            - Path=/users
        - id:
            create-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/signup
        - id:
            update-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/{userId}
#          filters:
#            - AuthorizationHeaderFilter
        - id:
            delete-user
          uri:
            lb://User-Service
          predicates:
            - Path=/users/{userId}
#          filters:
#            - AuthorizationHeaderFilter
        - id:
            user-login
          uri:
            lb://User-Service
          predicates:
            - Path=/users/login
token:
  expiration: 3600000
  secret: CYDblORrZAKg7i23rKlMi2lcwes9lUd8Q3D1GD1ViBm1NPvEKNnXGY6Fno7Ob8Vz