

spring:

  application:
    name: User-Service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/photographyDB
    username: postgres
    password: postgres
  security:
    user:
      name: user
      password: user
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8010/eureka
  instance:
    lease-renewal-interval-in-seconds: 5

gateway:
  ip: 10.0.0.46

token:
  expiration: 3600000
  secret: CYDblORrZAKg7i23rKlMi2lcwes9lUd8Q3D1GD1ViBm1NPvEKNnXGY6Fno7Ob8Vz

login:
  url:
    path: /users/login
signup:
  url:
    path: /users/signup