spring:
  application:
    name: DiscoveryService

server:
  port: 8010
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka
    tls:
      enabled: true
      key-store: /home/dan/Dev/Projects/photo-app/.dev-certs/myCertificate.jks
      key-store-type: JKS
      key-store-password: devpass
      trust-store: /home/dan/Dev/Projects/photo-app/.dev-certs/myCertificate.jks
      trust-store-type: PKCS12
      trust-store-password: devpass
  server:
    renewal-percent-threshold: 0.85

